spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        default-label: main
        git:
          uri: https://github.com/tarikbozkurt/config-server-t1
      profile: dev
server:
  port: 8888